SELECT 
 O.ORDERNUMBER,
 C.CUSTOMERNUMBER,
 C.CUSTOMERNAME,
 C.COUNTRY,
 C.CITY,
 O.ORDERDATE,
 O.REQUIREDDATE,
 O.SHIPPEDDATE,
 O.STATUS,
 OD.AMOUNT
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMERNUMBER = O.CUSTOMERNUMBER
JOIN
(
 SELECT ORDERNUMBER,SUM(PRICE) AS AMOUNT FROM ORDER_DETAILS
 GROUP BY ORDERNUMBER
) OD
ON O.ORDERNUMBER = OD.ORDERNUMBER
;

SELECT * FROM DATES
;